import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ContactIconRow from "~/components/ContactIcons";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>mudkip.live</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/sniff.ico" />
      </Head>


      <main className="bg-gradient-to-b from-gray-800 to-gray-900">
          {/* <div className="top-11 relative">
            <Navbar/>
          </div> */}
        <div className="min-h-screen flex flex-col align-center items-center justify-center">
          
          <h1 className="font-bold text-7xl text-white">General <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-blue-600">Mudkip</span></h1>
          <h1 className="text-white italic font-sans">(a.k.a Bence R)</h1>

          <div className="flex flex-row justify-center align-top mt-12 gap-x-10">
            <div className="card text-white">
              <h1 className="font-bold text-3xl">About</h1>
              <p className="text-xl mt-1">Hey, I'm a student always looking to work on improving. I'm currently learning Next.js, Tailwind, and React, alongside some others.</p>
            </div>
            <div className="card text-white">
              <h1 className="font-bold text-3xl">Contact</h1>
              <p className="text-xl mt-1">Want to reach out?</p>

              <ContactIconRow/>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;