import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#096faa] to-[#17598f]">
      <div className="flex flex-col items-center justify-center gap-12 align-top rounded-xl outline-offset-8 outline-double outline-8 outline-white">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              General <span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-sky-300">Mudkip</span>
            </h1>
            <h2 className="text-1xl italic text-white -mt-10">
              (a.k.a Bence Redmond)
            </h2>
          </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">About Me</h3>
              <div className="text-lg">
                Hey, I'm a student always looking to improve their CS skills.
              </div>
            </div>
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">Contact</h3>
              <div className="text-lg">
                Want to reach out?
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
